import "./globals.css";

export const metadata = {
  title: "Practice next13 crash course",
  description: "Generated by create next app",
  keywords: "nextjs, react, nodejs",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
